### ISSUE TITLE
release our block explorers to public use

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#30]
- [x] BTC explorer: http://btc.horizontalsystems.xyz
- [x] BCH explorer: http://bch.horizontalsystems.xyz
- [x] ETH explorer: http://eth.horizontalsystems.xyz (see also https://github.com/horizontalsystems/blockchain-meta/issues/4)
- [x]  for BTC/BCH we need a web GUI for block explorer (similar to https://eth.horizontalsystems.xyz). If there is a ready to use theme/plugin that comes with the BCOIN package then use it. Thi task can be delegated to @tmedetbekov by creating a separate issue for that. up to you

**Comment by nk-the-crazy** [comment]
Block-Explorers / API :
--------------
BTC-exp:  https://btc.horizontalsystems.xyz
BTC-API:  https://btc.horizontalsystems.xyz/apg/

BTC-Testnet-exp:  http://btc-testnet.horizontalsystems.xyz
BTC-Testnet-API:   http://btc-testnet.horizontalsystems.xyz/apg/
--------------
BCH -exp:  https://bch.horizontalsystems.xyz
BCH -API:  https://bch.horizontalsystems.xyz/apg/

BCH-Testnet-exp:  http://bch.horizontalsystems.xyz
BCH-Testnet-API:  http://bch.horizontalsystems.xyz/apg/
--------------
ETH-exp:  https://eth.horizontalsystems.xyz
(also available Geth Mainnet : https://eth-ext.horizontalsystems.xyz )
ETH-API:   https://eth.horizontalsystems.xyz/apg/

ETH-Testnet-exp:  http://eth-test.horizontalsystems.xyz
(also available Ropsten : http://eth-ropsten.horizontalsystems.xyz )
ETH-Testnet-API:   http://eth-test.horizontalsystems.xyz/apg/
