### ISSUE TITLE
enable clients to store/bookmark/label favorite wallet addresses and store them on IPFS 

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#31]
This feature would enable the client to associate payment addresses from various blockchains with specific labels/names. That list will be available to the user from the address field in SEND CONTROLLER. It would enable the user to auto-populate the address field by clicking on the label. 

The client would also display the label in a form of "to/from [name]" next to relevant transaction on TRANSACTIONS TAB.

What are requirements from the client side:

- [x] full confidentiality. only the user/client needs to be able to read/decrypt that data.
- [x] it shouldn't in any way jeopardize user's privacy
- [x] it should by no means put at risk user's Secret Keys. In other words whatever we use on the client side to identify the wallet, it shouldn't be related to Secret Key
- [x] the data should be available even if the user unlinks the wallet from device and restore it on a brand new app.

**Comment by nk-the-crazy** [comment]
Opened IPFS files api endpoints (for data storage) and secured with NGINX config.
(https://github.com/horizontalsystems/ipfs-configs)
Clients can use IPFS files api, generating uniq KEY (special KEY(HASH) belonging to wallet, generated by secure special methods.)
