### ISSUE TITLE
fee provider for Ethereum blockchain

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#32]
Just like we have for BTC and BCH we need a similar implementation for Ethereum blockchain. https://ipfs.horizontalsystems.xyz/ipns/Qmd4Gv2YVPqs6dmSy1XEq7pQRSgLihqYKL2JjK7DMUFPVz/io-hs/data/docs/block-explorer/bex-blockchain-fee.html

Please research the fee fundamentals on Ethereum and create a smart logic that would recommend user the optimal fees for a given moment

**Comment by nk-the-crazy** [comment]
Implemented using INFURA rpc methods.
