### ISSUE TITLE
List of ERC20 tokens supported by bank wallet

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#34]
The client team just completed the coin manager controller from where user will be able to select which coins to display on the balance tab.

What we need is the curated list of supported ERC 20 tokens hosted on IPFS. The wallet will read/download supported ERC 20 tokens from IPFS and retrieve the needed data from the source to display the given token and relevant data (such as icon icon, name, symbol etc) in the wallet. all the data will be provided, we only need read-only storage that will be accessible to all clients.

We need this before January 24'th

**Comment by esengulov** [comment]
@uberkerim below is the initial list. It's mainly from coinmarketcap top 100 list and for the most part lists only projects that have a product and/or real clients

**ERC20 Tokens** :  

- Binance Coin
- Maker OmiseGo 0x
- Basic Attention token
-  PundiX
- ChainLink
- Populous
- TrueUSD
- Tether 
- Golem
-  Augur
- USDCoin 
- Paxos Standard Token 
- Status 
- Waltonchain 
- Decentraland
-  Mithril 
- Kucoin 
- Digix 
- Kyber network
-  Loom Network
-  Zilliqa
-  Gemini Dollar
-  Dai 
- Revain 
- Huobi Token
-  Crypto.com 
- DigixDAO
- Stasis EURS
- Polymath 
- Nexo 
- Bancor
-  Kucoin Shares

**Comment by nk-the-crazy** [comment]
ERC20 tokens data upload into IPFS (/io-hs/data/blockchain/ETH/erc20tokens).
