### ISSUE TITLE
Setup block explorer for Ethereum blockchain

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#4]
- [x] main net
- [x]  test net

**Comment by nk-the-crazy** [comment]
Forked https://github.com/gobitfly/etherchain-light AS https://github.com/horizontalsystems/etherchain-light.  Removed forked libraries (web3 JS) from the source and reimplemented using origin Web3 library.

**Comment by nk-the-crazy** [comment]
Blockscout BE, was setup on EC2 instances.
Latest updates on ETH block explorers:

https://eth.horizontalsystems.xyz   --> Mainnet Parity
https://eth-ext.horizontalsystems.xyz  --> Mainnet Geth
http://eth-ropsten.horizontalsystems.xyz  --> Ropsten-Testnet (Geth)

----------------------------------------
