### ISSUE TITLE
Implement alternative X-Rates handler to CryptoCompare

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/blockchain-meta#40]
Research and implement  free Open-Source Xrates API alternatives to CryptoCompare.
Xrates API should have basic support for BTC,BCH and ETH cryptos and historical data at least for 1 month.

**Comment by uberkerim** [comment]
https://www.bitmex.com/app/apiOverview

Bitmex is one of the biggest crypto exchanges.

**Comment by uberkerim** [comment]
https://www.kraken.com/features/websocket-api

Kraken is one of the biggest american crypto exchanges. Very popular in Europe, especially in Germany.

**Comment by nk-the-crazy** [comment]
Found free alternatives 
1. https://api.coinpaprika.com
2. https://www.cryptonator.com/api/

**Comment by nk-the-crazy** [comment]
Implemented handler for https://api.coinpaprika.com as a alternative (backup) to CryptoCompare
