### ISSUE TITLE
Provide Exchange Rates for ERC20 tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#41]
- [x] With the addition of support for ERC20 tokens we need current exchange rates for newly added tokens. 
- [ ] if you're able to retrieve the historical rates for tokens please add those as well. If there are issues with the task let's discuss it.

**Comment by nk-the-crazy** [comment]
Historical rates to 01.01.2017 provided

**Comment by nk-the-crazy** [comment]
Historical rates to 01.01.2016 provided
