### ISSUE TITLE
Make sure that exchange rate data for erc20 tokens shown in BANK wallet is within the reasonable range

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#42]
Note: Work on this issue only when exchange rate data for erc20 tokens is already available on HS IPFS node. https://github.com/horizontalsystems/blockchain-meta/issues/41

Consider following setup in BANK wallet:
- language: Korean
- base currency:  Korean Won

Consider a case when a user decides to send a 100KRW worth of BNB (ERC20) tokens. On send controller the user enters 100$ and the wallet calculates the respective amount in BNB tokens.

The BANK wallet will lookup the provided KRW/BNB rate and calculate the amount. However, it should be noted that the rate wallet provided with is in itself obtained from two other rates: 

- the BNB/USD rate
- USD/KRW

Since the BNB/KRW rate is not really a market rate but the derived from two other rates it's likely to be somewhat different from a real market rate. What we need to make sure is that the rates shown in the BANK wallet don't deviate more than 1-3% from the actual rate. 

Therefore,  please do following: 

1. lookup current market rates for some highly traded ERC20 tokens on local exchanges(in Korea, Japan). 
2. Get real current rates for ERC20/base_currency rates, where base_currency is a currency of that locality.
3. compare real market rate to the rate derived by the BANK wallet for that pair.
4. measure the difference in %
5. post findings in comments

**Comment by uberkerim** [comment]
Let's pick one coin, for example PPT.

On Bithumb (largest Korean exchange) its price at present is 1348 KRW or $1.20
In Bank wallet its price at present it 1359 KRW or $1.21

As you can see the difference is 1%. As per my observation differences in prices can be up to 3%. And the reason for that is not conversion between currencies, but the source of prices. Asian exchanges have slightly lower prices. For example BTC price on Bithumb is $3541, while on Binance it is $3603, on Coinbase $3568 and on CryptoCompare $3602.

**Comment by uberkerim** [comment]
For example WTC coin on Korean exchange costs 1104 KRW or $0.98 (both values from Bithumb)
While in Bank wallet app its price is 1117 KRW or $0.99
This 1% difference is attributed to difference in actual prices (each exchange has different price) rather than due to currency conversion arithmetics.
Thus I conclude that currency conversions are reliable, and have negligible impact on price.
