### ISSUE TITLE
update ERC20 contracts list

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#43]
- [ ] updated json index file. It now points to properly formatted contract addresses: https://github.com/horizontalsystems/ERC20-coin-reference/commit/4ffd61279089ef26dff0fe104390fa01667248ae

- [ ] update the icon locations for each contract. the folder name for some ERC20-contract icons should match the contract address (case sensitive)

**Comment by nk-the-crazy** [comment]
Main index.json and  ErC20 tokens addresses updated.
