### ISSUE TITLE
Make sure that Horizontal Systems ETH node supports light clients

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#52]
We would like to ensure that full node that we run able too communicate and interact with ETH light clients. 

As we progress through light client development we would like to work with our own light node while we are at development stage. It's likely that our node already has this in place but you need to make sure.

**Comment by nk-the-crazy** [comment]
Deployed Testnet Geth Node on , 
https://eth-testnet.horizontalsystems.xyz:30303
