### ISSUE TITLE
Add new ERC20 Tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/blockchain-meta#55]
- [x] Aurora DAO
-- contract address: 0xCdCFc0f66c522Fd086A1b725ea3c0Eeb9F9e8814

- [x] EnjinCoin
-- contract address: 0xF629cBd94d3791C9250152BD8dfBDF380E2a3B9c 

- [x] Wax
contract address:  0x39Bb259F66E1C59d5ABEF88375979b4D20D98022

- [x] IDXM
contract address: 0xCc13Fc627EFfd6E35D2D2706Ea3C4D7396c610ea

**Comment by TalgatNurdinov** [comment]
[new_erc20_icons.zip](https://github.com/horizontalsystems/blockchain-meta/files/3011614/new_erc20_icons.zip)

**Comment by TalgatNurdinov** [comment]
[new_erc20_2.zip](https://github.com/horizontalsystems/blockchain-meta/files/3017529/new_erc20_2.zip)

**Comment by nk-the-crazy** [comment]
New ERC20 tokens added xrates support.

**Comment by esengulov** [comment]
@Dianaaiym needs to be reviewed/accepted
