### ISSUE TITLE
Add new ERC20 Tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/blockchain-meta#59]
- [x] USDT
contract address:  0xdAC17F958D2ee523a2206206994597C13D831ec7
starting date: Mar 6, 2015

- [x] Holo (HOT)
contract address: 0x6c6EE5e31d828De241282B9606C8e98Ea48526E2
starting date: May 1, 2018

- [x] Crypto.com chain (CRO)
contract address: 0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b
starting date: Dec 14, 2018

- [x] IOST
contract address: 0xFA1a856Cfa3409CFa145Fa4e20Eb270dF3EB21ab
starting date: Jan 16, 2018

- [x] Loopring (LRC)
contract address: 0xEF68e7C694F40c8202821eDF525dE3782458639f
starting date: Aug 30, 2017

- [x] aelf (ELF)
contract address: 0xbf2179859fc6D5BEE9Bf9158632Dc51678a4100e
starting date: Dec 22, 2017

- [x] orbs (ORBS)
contract address: 0xff56Cc6b1E6dEd347aA0B7676C85AB0B3D08B0FA
starting date: Apr 3, 2019

- [ ] @TalgatNurdinov please attach icon for this coin

**Comment by nk-the-crazy** [comment]
Please add details about the token. Starting date, icons  etc. @Dianaaiym 
This will help to fetch historical rates.

**Comment by TalgatNurdinov** [comment]
https://github.com/horizontalsystems/HS-Design/tree/master/icons

**Comment by Dianaaiym** [comment]
> Please add details about the token. Starting date, icons etc. @Dianaaiym
> This will help to fetch historical rates.

from March 6, 2015

**Comment by TalgatNurdinov** [comment]
[erc20icons.ios.26.04.zip](https://github.com/horizontalsystems/blockchain-meta/files/3119862/erc20icons.ios.26.04.zip)
[erc20icons.andr.26.04.zip](https://github.com/horizontalsystems/blockchain-meta/files/3119864/erc20icons.andr.26.04.zip)
[erc20icons.svg.26.04.zip](https://github.com/horizontalsystems/blockchain-meta/files/3119866/erc20icons.svg.26.04.zip)

**Comment by TalgatNurdinov** [comment]
[usdt_ios.zip](https://github.com/horizontalsystems/blockchain-meta/files/3121178/usdt_ios.zip)
[usdt_andr.zip](https://github.com/horizontalsystems/blockchain-meta/files/3121179/usdt_andr.zip)
[usdt.svg.zip](https://github.com/horizontalsystems/blockchain-meta/files/3121183/usdt.svg.zip)

**Comment by nk-the-crazy** [comment]
Historical rates added until 1 Jan 2016
