### ISSUE TITLE
Prepare data sources for the price change graphs

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#69]
![67ecbc28-4302-4022-8d72-3249569ea93b](https://user-images.githubusercontent.com/8611762/59900023-b0eda100-9418-11e9-9cd3-6f4f12427177.jpg)

The client needs to be able to show graphs for price changes. We need stats for:

- 1 DAY
- 1 WEEK
- 1 MONTH
- 3 MONTH
- 6 MONTH
- 1 YEAR
- 2 YEARS

we also need to compute and serve following values:

- market cap
- 52 week high
- 52 week low

**Comment by nk-the-crazy** [comment]
Added following data sources for graphs :

DAILY -> Scale : 30 min , 48 points
1 WEEK -> Scale : 3 Hours , 56 points
1 MONTH -> Scale : 12 hours , 60 points
6 MONTH -> Scale : 3 days , 60 points
1 YEAR -> Scale : 7 days , 52 points

**Comment by nk-the-crazy** [comment]
3 month and 2 Years removed to optimize IPFS performance

**Comment by nk-the-crazy** [comment]
URL for graph data :
IPFS-URL/ipns/[peer_id]/xrates/stats/[FIAT]/[COIN]/

https://ipfs-ext.horizontalsystems.xyz/ipns/QmXTJZBMMRmBbPun6HFt3tmb3tfYF2usLPxFoacL7G5uMX/xrates/stats/USD/BTC
