### ISSUE TITLE
start collecting rates for EOS based tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#71]
We are currently integrating EOS into the wallet and therefore need you to collect current market prices for the following tokens:

Based on the previous discussion about this you mentions that we have rates only for 4 of them (https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/694#issuecomment-505856985), so just collect prices only for those.

- EOS 
- NDX
- IQ
- EOSDT
- NUT
- PGL
- MEETONE 
- PTI

**Comment by nk-the-crazy** [comment]
Added Xrates support for Tokens below :

1. EOS    -- OK
2. NDX    -- ?
3. IQ       -- OK
4. EOSDT  -- OK (available only Historical data, no latest rates for now)
5. NUT    -- ?
6. PGL    -- OK
7. MEETONE - OK
8. PTI    -- OK
