### ISSUE TITLE
start collecting rates for Binance and BEP2 tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#72]
here is the list we are starting with, horizontalsystems/unstoppable-wallet-android#1085

let us know if you are not able to get rates for any of the tokens.

**Comment by nk-the-crazy** [comment]
By using CryptoCompare only for:
GTO
ANKR
CRPT
CAS
We can try to use Binance-Dex api.

**Comment by esengulov** [comment]
> By using CryptoCompare only for:
> GTO
> ANKR
> BTCB
> CRPT
> CAS
> We can try to use Binance-Dex api.

cooL, let's use CryptoCompare

**Comment by nk-the-crazy** [comment]
Added xrates support for:
1.GTO
2.ANKR
3.BTCB
4.CRPT
5.CAS
