### ISSUE TITLE
Return estimate transaction duration in seconds along with fee rates for each blockchain

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#78]
the approximate duration should be provided for all values:

- econom
- medium
- priority

**Comment by nk-the-crazy** [comment]
Need to provide following data together with fee data (format should be in seconds)
Bitcoin:
Urgent: 30 min
Medium: 2 hours
Econom: 24 hours
Bitcoin Cash:
Urgent: 30 min
Medium: 2 hours
Econom: 4 hours
Ethereum
Urgent: 2 min
Medium: 5 min
Econom: 30 min

**Comment by nk-the-crazy** [comment]
New JSON format :

https://ipfs-ext.horizontalsystems.xyz/ipns/QmXTJZBMMRmBbPun6HFt3tmb3tfYF2usLPxFoacL7G5uMX/blockchain/estimatefee/feerates.json
