### ISSUE TITLE
Add exchange rates for NUT, BNB-ERC20, IDEX token

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#79]
- [x] start parsing exchange rates for NUT token. https://www.cryptocompare.com/coins/nut/overview/USD
- [ ] add BNB-ERC20 coin symbol to rates JSON. it should have same rates as regular BNB. Both current and historical rates.
- [x] add rate for IDEX token, https://www.cryptocompare.com/coins/idex/overview
- [x] the rate for IDEX token is identical to Aurora DAO token. It's the token, deployed on different ERC20 contracts

**Comment by nk-the-crazy** [comment]
Support for BNB-ERC20 will be added on Clients.

**Comment by nk-the-crazy** [comment]
Support added for NUT, IDEX and HOT (Holo) tokens
